#------------------------------------------------------------------------------
# written by: mcdaniel
# date: june-2022
#
# usage: top-level workflow. Initiated manually from Github Actions console page
#        Builds all Docker containers.
#------------------------------------------------------------------------------
name: Build Optional Containers

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENABLE_MFE: true
      ENABLE_BACKUP: false
      ENABLE_CREDENTIALS: false
      ENABLE_LICENSE_MANAGER: false

      # environment settings
      # --------------------------------------------
      SUBDOMAIN: courses
      DOMAIN_NAME: openedx-devops.abzt.de
      SITE_NAME: abzt-openedx
      AWS_REGION: eu-north-1
      ENVIRONMENT_ID: prod
      NAMESPACE: abzt-openedx-eu-prod
      EKS_CLUSTER_NAME: abzt-openedx-eu-service
      S3_BUCKET_PREFIX: abzt-openedx-eu-prod

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Initialize environment
        uses: openedx-actions/tutor-k8s-init@v1.0.9
        with:
          eks-namespace: ${{ env.NAMESPACE }}
          eks-cluster-name: ${{ env.EKS_CLUSTER_NAME }}
          aws-region: ${{ env.AWS_REGION }}
          tutor-version: "15.3.8"
          tutor-mfe-version: "15.0.7"
          kubectl-version: "1.27"

      - name: Build MFE
        if: ${{ env.ENABLE_MFE == 'true' }}
        uses: openedx-actions/tutor-plugin-build-mfe@v0.1.6

      - name: Build Backup
        if: ${{ env.ENABLE_BACKUP == 'true' }}
        uses: openedx-actions/tutor-plugin-build-backup@v0

      - name: Build Credentials
        if: ${{ env.ENABLE_CREDENTIALS == 'true' }}
        uses: openedx-actions/tutor-plugin-build-credentials@v1
        with:
          version: latest
          aws-ecr-repo: openedx_credentials

      - name: Build License Manager
        if: ${{ env.ENABLE_LICENSE_MANAGER == 'true' }}
        uses: openedx-actions/tutor-plugin-build-license-manager@v0.0.2
